[package]
name = "yubi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
async-std = { version = "1.10.0", features = ["attributes"] }
async-trait = "0.1.51"
clap = "3.0.0-beta.5"
env_logger = "0.9.0"
googapis = { version = "0.5.0", features = ["google-container-v1"] }
gouth = { version = "0.2.1" }
log = "0.4.14"
prost = "0.9.0"
prost-types = "0.9.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
tokio = { version = "1.13.0", features = ["rt-multi-thread", "time", "fs", "macros"] }
tonic = { version = "0.6.1", features = ["tls"] }

[dev-dependencies]
mockall = "0.10.2"
rstest = "0.11.0"
