name: renovate

on:
  workflow_dispatch:
  schedule:
    # run at JST 18:00 everyday
    - cron: "0 9 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run renovate
        uses: renovatebot/github-action@v32.3.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
